export const RELOAD = 'reload';
export const DELETE = 'delete';
export const SEARCH = 'search';

// CLEAN
export const CLEAN_ALL = 'CLEAN_ALL';
export const CLEAN_STATE = 'CLEAN_STATE';
// CHANGE
export const CHANGE_SCREEN_STATE = 'CHANGE_SCREEN_STATE';
export const CHANGE_STATE = 'CHANGE_STATE';
export const CHANGE_ALERT_STATE = 'CHANGE_ALERT_STATE';

// LOGIN

export const LOGIN = 'LOGIN';

export const SET_PASS_BACKUP = 'SET_PASS_BACKUP';


export const FILTER_MARKET = 'FILTER_MARKET';
//ID session
export const ID_SESSION = 'ID_SESSION';
//STEP
export const STEP = 'STEP';
// SET_USER 
export const SET_USER = 'SET_USER';
// SET_SHOE_CURRENT_WEAR
export const SET_SHOE_CURRENT_WEAR = 'SET_SHOE_CURRENT_WEAR';
// GET_RATE 
export const GET_RATE = 'GET_RATE';
export const GET_RATE_SUCCESS = 'GET_RATE_SUCCESS';
export const GET_RATE_FAILURE = 'GET_RATE_FAILURE';
// GET_RATE 
export const GET_RATE_BNB = 'GET_RATE_BNB';
export const GET_RATE_BNB_SUCCESS = 'GET_RATE_BNB_SUCCESS';
export const GET_RATE_BNB_FAILURE = 'GET_RATE_BNB_FAILURE';
// SWAP 
export const SWAP = 'SWAP';
export const SWAP_SUCCESS = 'SWAP_SUCCESS';
export const SWAP_FAILURE = 'SWAP_FAILURE';
// TRANSFER 
export const TRANSFER = 'TRANSFER';
export const TRANSFER_SUCCESS = 'TRANSFER_SUCCESS';
export const TRANSFER_FAILURE = 'TRANSFER_FAILURE';
// TRANSFER_SPENDING 
export const TRANSFER_SPENDING = 'TRANSFER_SPENDING';
export const TRANSFER_SPENDING_SUCCESS = 'TRANSFER_SPENDING_SUCCESS';
export const TRANSFER_SPENDING_FAILURE = 'TRANSFER_SPENDING_FAILURE';


// TOTALKM 
export const TOTALKM = 'symb: type,';
export const TOTALKM_SUCCESS = 'TOTALKM_SUCCESS';
export const TOTALKM_FAILURE = 'TOTALKM_FAILURE';
// TRANSFER_SPENDING 
export const GET_CONST_SHOE = 'GET_CONST_SHOE';
export const GET_CONST_SHOE_SUCCESS = 'GET_CONST_SHOE_SUCCESS';
export const GET_CONST_SHOE_FAILURE = 'GET_CONST_SHOE_FAILURE';
// IS_STEP_TIME
export const IS_STEP_TIMER = 'IS_STEP_TIMER';

// RESEND_REGISTER_CODE
export const RESEND_REGISTER_CODE = 'RESEND_REGISTER_CODE';
export const RESEND_REGISTER_CODE_SUCCESS = 'RESEND_REGISTER_CODE_SUCCESS';
export const RESEND_REGISTER_CODE_FAILURE = 'RESEND_REGISTER_CODE_FAILURE';

// API_POST_SUBMIT_CODE
export const SUBMIT_CODE = 'SUBMIT_CODE';
export const SUBMIT_CODE_SUCCESS = 'SUBMIT_CODE_SUCCESS';
export const SUBMIT_CODE_FAILURE = 'SUBMIT_CODE_FAILURE';

// API_POST_SET_PASSWORD
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS';
export const SET_PASSWORD_FAILURE = 'SET_PASSWORD_FAILURE';
// API_POST_SET_PASSWORD
export const CHECK_PASSWORD = 'SET_PASSWORD';
export const CHECK_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS';
export const CHECK_PASSWORD_FAILURE = 'SET_PASSWORD_FAILURE';
// API_POST_LOGIN
export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';

// API_GET_USER_INFO
export const USER_INFO = 'USER_INFO';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE';

// API_PUT_CHANGE_INFO
export const CHANGE_INFO = 'CHANGE_INFO';
export const CHANGE_INFO_SUCCESS = 'CHANGE_INFO_SUCCESS';
export const CHANGE_INFO_FAILURE = 'CHANGE_INFO_FAILURE';

// API_PUT_CHANGE_PASSWORD
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

// API_POST_SUBMIT_CHANGE_PASSWORD
export const SUBMIT_CHANGE_PASSWORD = 'SUBMIT_CHANGE_PASSWORD';
export const SUBMIT_CHANGE_PASSWORD_SUCCESS = 'SUBMIT_CHANGE_PASSWORD_SUCCESS';
export const SUBMIT_CHANGE_PASSWORD_FAILURE = 'SUBMIT_CHANGE_PASSWORD_FAILURE';

// API_GET_MARKET
export const MARKET = 'MARKET';
export const MARKET_SUCCESS = 'MARKET_SUCCESS';
export const MARKET_FAILURE = 'MARKET_FAILURE';


// MARKET_BACKUP
export const FILTER_BACKUP = 'FILTER_BACKUP';
export const MARKET_BACKUP_SUCCESS = 'MARKET_BACKUP_SUCCESS';
export const MARKET_BACKUP_FAILURE = 'MARKET_BACKUP_FAILURE';

// API_GET_SHOES_ID
export const GET_SHOES_ID = 'GET_SHOES_ID';
export const GET_SHOES_ID_SUCCESS = 'GET_SHOES_ID_SUCCESS';
export const GET_SHOES_ID_FAILURE = 'GET_SHOES_ID_FAILURE';

// API_PUT_SHOES_ID
export const PUT_SHOES_ID = 'PUT_SHOES_ID';
export const PUT_SHOES_ID_SUCCESS = 'PUT_SHOES_ID_SUCCESS';
export const PUT_SHOES_ID_FAILURE = 'PUT_SHOES_ID_FAILURE';

// API_GET_SHOES
export const SHOES = 'SHOES';
export const SHOES_SUCCESS = 'SHOES_SUCCESS';
export const SHOES_FAILURE = 'SHOES_FAILURE';

// API_GET_SHOES_CONSTANTS
export const SHOES_CONSTANTS = 'SHOES_CONSTANTS';
export const SHOES_CONSTANTS_SUCCESS = 'SHOES_SUCCESS';
export const SHOES_CONSTANTS_FAILURE = 'SHOES_FAILURE';

// API_POST_BUY
export const BUY = 'BUY';
export const BUY_SUCCESS = 'BUY_SUCCESS';
export const BUY_FAILURE = 'BUY_FAILURE';

// API_POST_PRIVATE_ASSIGN_SHOES
export const PRIVATE_ASSIGN_SHOES = 'PRIVATE_ASSIGN_SHOES';
export const PRIVATE_ASSIGN_SHOES_SUCCESS = 'PRIVATE_ASSIGN_SHOES_SUCCESS';
export const PRIVATE_ASSIGN_SHOES_FAILURE = 'PRIVATE_ASSIGN_SHOES_FAILURE';

// API_GET_SHOES_ID_WEAR
export const SHOES_ID_WEAR = 'SHOES_ID_WEAR';
export const SHOES_ID_WEAR_SUCCESS = 'SHOES_ID_WEAR_SUCCESS';
export const SHOES_ID_WEAR_FAILURE = 'SHOES_ID_WEAR_FAILURE';

// API_GET_USER_ID
export const USER_ID = 'USER_ID';
export const USER_ID_SUCCESS = 'USER_ID_SUCCESS';
export const USER_ID_FAILURE = 'USER_ID_FAILURE';

// API_GET_USER_ID
export const USER_ID_BNB = 'USER_ID_BNB';
export const USER_ID_BNB_SUCCESS = 'USER_ID_BNB_SUCCESS';
export const USER_ID_BNB_FAILURE = 'USER_ID_BNB_FAILURE';


// API_PASS_CODE_WALLET
export const PASS_CODE_WALLET = 'PASS_CODE_WALLET';
export const PASS_CODE_WALLET_SUCCESS = 'PASS_CODE_WALLET_SUCCESS';
export const PASS_CODE_WALLET_FAILURE = 'PASS_CODE_WALLET_FAILURE';
// API_POST_UPDATE_MONEY
export const UPDATE_MONEY = 'UPDATE_MONEY';
export const UPDATE_MONEY_SUCCESS = 'UPDATE_MONEY_SUCCESS';
export const UPDATE_MONEY_FAILURE = 'UPDATE_MONEY_FAILURE';

// API_POST_RUN
export const RUN = 'RUN';
export const RUN_SUCCESS = 'RUN_SUCCESS';
export const RUN_FAILURE = 'RUN_FAILURE';

// API_GET_RUNNING_SESSION_ID
export const GET_RUNNING_SESSION_ID = 'GET_RUNNING_SESSION_ID';
export const GET_RUNNING_SESSION_ID_SUCCESS = 'GET_RUNNING_SESSION_ID_SUCCESS';
export const GET_RUNNING_SESSION_ID_FAILURE = 'GET_RUNNING_SESSION_ID_FAILURE';

// API_PUT_RUNNING_SESSION_ID
export const PUT_RUNNING_SESSION_ID = 'PUT_RUNNING_SESSION_ID';
export const PUT_RUNNING_SESSION_ID_SUCCESS = 'PUT_RUNNING_SESSION_ID_SUCCESS';
export const PUT_RUNNING_SESSION_ID_FAILURE = 'PUT_RUNNING_SESSION_ID_FAILURE';
