require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

#useMapLibre = false

#if useMapLibre
#  $ReactNativeMapboxGLIOSVersion = '~> 6.1'
#  $RNMBGL_Use_SPM = true
  $RNMBGL_Use_SPM = {
      url: "https://github.com/maplibre/maplibre-gl-native-distribution",
      requirement: {
        kind: "upToNextMajorVersion",
        minimumVersion: "5.12.0"
      },
      product_name: "Mapbox"
    }
  $RNMGL_USE_MAPLIBRE = true
#end

target 'step' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  # Mapbox
#  pod 'Mapbox-iOS-SDK', '~> 4.11.2'
#  pod 'MapboxMobileEvents', '~> 0.10.2'
  pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'
#  pod 'react-native-mapbox-gl/DynamicLibrary', :path => '../node_modules/@react-native-mapbox-gl/maps'

  #use_frameworks!
  
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'


  pre_install do |installer|
      $RNMBGL.pre_install(installer)
    end
  
  target 'stepTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    $RNMBGL.post_install(installer)
  end
end
